### ISSUE TITLE
如何设置单个页面中的page背景色，不是page.json中的backgroundColor？

### ISSUE THREAD

**Issue by tangOldhan** [Tencent/wepy#1317]
## Description
目前需求是设置单个页面整体的背景色，不是原生中的`page.json`中的配置。
使用原生小程序的写法可以在单个页面文件的`.wxss` 文件中书写page的样式
```css
page {
    background-color: #f3f3f3
}
```
但是使用`wepy`，在单个`.wpy`文件的`<style>`标签中设置page的背景色无效

请问如何可以设置page的背景色；

**Comment by Gcaufy** [comment]
style标签中的内容也是生成 到wxss中的，可以参考看一下dist目录里面的内容 。

**Comment by tangOldhan** [comment]
@Gcaufy 多谢提醒，我找到问题在哪了，但是不知道为什么会造成这样的效果。
不生效的代码是这样写的：
```html
<style lang="less" scoped>
    page {
        background-color: #f3f3f3;
   }
</style>
```
对应dist目录下`wxss`的内容
```css
page._ebc9a16 {
  background-color: #f3f3f3;
}
```
就是这个`scoped` 属性造成的，但是具体为什么会产生这种效果，我就不太清楚了，我再去查查吧。
