### ISSUE TITLE
关于数据绑定的几个问题

### ISSUE THREAD

**Issue by Jam1zhu** [Tencent/wepy#1719]
用vue开发习惯了，wepy的亮点之一也是贴近vue的开发思路。刚看完文档，尝试写了写，遇到了几个问题，请大神们帮忙解决下。

### 条件渲染
在wepy中还是需要写成小程序的条件语句吗？尝试了几种写法
有没有不加花括号能实现的形式？
```javascript
  wx:if="{{condition}}"     // 可行
  wx-if="{{condition}}"   // 可行
  :if="{{condition}}"    //error
  wx:if="condition"    // error
  wx-if="condition"   //error
```

### 数据绑定
repeat出来的数据绑定，原生组件只能通过{{}}才能绑定吗？自定义组件用冒号绑定？
下面这段代码是可行的
```javascript
  <repeat for="{{arr}}" key="index" index="index">
      <image src="{{item.src}}" data-index="{{index}}"></image>
      <selfCom :des="item.des"></selfCom>
    </repeat>
```
下面这段代码不可行
```javascitpt
<repeat for="{{demoArr}}" key="index" index="index">
      <image :src="item.src" :data-index="index"></image>
      <demoCom :des="item.des"></demoCom>
</repeat>
```
不是说非要跟vue开发一样，而是一个框架的绑定方式，至少是要统一的吧，要么统一成{{}}，要么统一成vue的绑定方式。

*********************

### 还有个小问题 css的单位问题
```css
 image{
    width: 100rpx;     //可行
    width: 100 rpx;    // 不起作用，很尴尬，webstrom的格式化，会在100和rpx之间加个空格，
 // 这样编译之后的数据，小程序无法识别。求大神赐教怎么解决！！！
}
```

最后，如果是我本人使用的有问题，请大神们轻喷，如果有统一用法的话，就太棒了。很喜欢这个框架，很优秀，个人觉得项目管理比小程序自身的方便一些。
