### ISSUE TITLE
【新语法讨论】import 语法的意见收集

### ISSUE THREAD

**Issue by Gcaufy** [Tencent/wepy#1855]
在使用 less/sass/stylus 时，会用到 @import 语句，页面A和页面B 同时 import 了同一个文件时，实际上这个文件被被分别编译进了 a.wxss 和 b.wxss。
实际上小程序是支持@import 语法的，所以这一部分不用重复编译的

因此，参考 Less 的 [import-options](http://www.css88.com/doc/less/features/#import-options-) 考虑新添加一个import 语法防止重复编译。

Less:
```
import (weapp) './common';
```

**Comment by Gcaufy** [comment]
@ymqq 
有些公用文件用户会单独放在 common.wxss 
然后 page1, page2, page3 分别都 @import common.wxss

那不就是这个common被分别编译进了三个文件了么？代码量翻了三倍

**Comment by ishen7** [comment]
> @ymqq
> 有些公用文件用户会单独放在common.wxss 
> 然后第1页，第2页，第3页分别都@import common.wxss
> 
> 那不就是这个共同被分别编译进了三个文件了么？代码量翻了三倍

小程序本身就支持import语法。不需要将其编译复制到引用目的位置，

eg:
```css
/* common.wxss */
page {
  display: flex;
}
```
```css
/* page.wxss */
@import common.wxss

/* page styles */

```

编译后结果
```css
/* common.wxss */
page {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
}
```

```css
/* page.wxss */
@import common.wxss

/* page styles */

```
那程序只需要对common.wxss进行编译，页面的wxss无需做任何改动。(我认为应该是这样)
