### ISSUE TITLE
scss里存在\等字符导致微信开发者工具报样式错误

### ISSUE THREAD

**Issue by Bulandent** [Tencent/wepy#2650]
比如有一个文件 `icon.wpy`，然后这个文件引入了字体图标，有如下的样式代码：
``` scss
<style lang="scss" type="text/scss">
    .icon {
        font-size: 16px;
        &.success::after {
            content: '\e69e';
            color: red;
        }
    }
</style>
```
那么微信开发者工具有就报如下错误：
``` 
Error:

in File: ./icon/icon.wxss

unexpected "?" at pos 1
> 1 | .con{font-size:16px;&.success::...
```
但是如果把 `content: '\e69e';` 去掉 `\` 则不会报错。
