### ISSUE TITLE
wepy2 scss 中添加字体图标样式，编译后报错

### ISSUE THREAD

**Issue by FreeRide-Joe** [Tencent/wepy#2674]
## 问题描述
在 scss 中 添加字体图标样式，编译后报错
图标的 `content: "\e651"` 在编译后生成的 未知字符 开发者工具无法识别，导致报错

![image](https://user-images.githubusercontent.com/16112889/89377630-ce68f180-d724-11ea-80be-ca769b70287d.png)

![image](https://user-images.githubusercontent.com/16112889/89378190-e42ae680-d725-11ea-9384-0e7421a0325d.png)

## 环境
  * Platform: 开发者工具
  * Platform version: RC 1.03.2006091
  * wepy-cli version: 2.1.0
  * wepy version: 2.0.0-alpha.16
  
## 复现步骤
在app.wpy中添加如下代码：
```css
<style lang="scss">
    .ss-icon-share:before {
        content: "\e651";
    }
</style>
```
